
import difflib, os
from typing import List, Dict, Any
from services.common.schemas import CriticReview, FilePatch

def build_unified_diff(original: str, updated: str, path: str) -> str:
    a = original.splitlines(keepends=True)
    b = updated.splitlines(keepends=True)
    return ''.join(difflib.unified_diff(a, b, fromfile=f"{path} (orig)", tofile=f"{path} (new)"))

def propose_patches(files: List[Dict[str,Any]]) -> Dict[str, Any]:
    patches = []
    explains = []
    for f in files:
        path = f.get("path")
        current = f.get("current","")
        candidate = f.get("candidate","")
        if current == candidate:
            continue
        diff = build_unified_diff(current, candidate, path)
        patches.append({"path": path, "type":"replace", "content": candidate})
        explains.append(f"Replace {path} to match generated candidate; lines changed: {diff.count('\n')}")
    review = {
        "verdict":"accept" if patches else "block",
        "notes":"Generated by real critic; accepting simple replace patches" if patches else "No changes necessary",
        "fix_recommendations":[{"step_id":"auto", "patch_request":{"patches":patches}}] if patches else []
    }
    return review
